name             'laptop-init'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures laptop-init'
long_description 'Installs/Configures laptop-init'
version          '0.1.0'

depends 'desktop'
depends 'dropbox'
depends 'postgresql'
depends 'python'
